name: Commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: "m2-repo-${{ hashFiles('project.clj') }}"
      - name: Run tests
        run: lein test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.01.15'
      - name: Run clj-kondo
        run: clj-kondo --lint src --lint test
